version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: elevators-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./alldb.sql:/docker-entrypoint-initdb.d/alldb.sql
    ports:
      - "3307:3306"

  adminer:
    container_name: elevators-adminer
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080