version: '3.1'

services:
  db:
    image: mysql
    container_name: elevators-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  adminer:
    container_name: elevators-adminer
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-dump:
